// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyStore.Data;

#nullable disable

namespace MyStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427183741_addpublisherfieldtviewmodel")]
    partial class addpublisherfieldtviewmodel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MyStore.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MyStore.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("ImageUrl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("cat.png");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            ImageUrl = "https://picsum.photos/seed/electronics/400/300",
                            Name = "Electronics"
                        },
                        new
                        {
                            CategoryId = 2,
                            ImageUrl = "https://picsum.photos/seed/home/400/300",
                            Name = "Home Appliances"
                        },
                        new
                        {
                            CategoryId = 4,
                            ImageUrl = "https://picsum.photos/seed/computer/400/300",
                            Name = "Computer Devices"
                        },
                        new
                        {
                            CategoryId = 5,
                            ImageUrl = "https://picsum.photos/seed/gaming/400/300",
                            Name = "Gaming"
                        },
                        new
                        {
                            CategoryId = 6,
                            ImageUrl = "https://picsum.photos/seed/office/400/300",
                            Name = "Office Supplies"
                        },
                        new
                        {
                            CategoryId = 7,
                            ImageUrl = "https://picsum.photos/seed/wearables/400/300",
                            Name = "Smart Wearables"
                        },
                        new
                        {
                            CategoryId = 8,
                            ImageUrl = "https://picsum.photos/seed/kitchen/400/300",
                            Name = "Kitchen Tools"
                        },
                        new
                        {
                            CategoryId = 9,
                            ImageUrl = "https://picsum.photos/seed/sports/400/300",
                            Name = "Sports Equipment"
                        },
                        new
                        {
                            CategoryId = 10,
                            ImageUrl = "https://picsum.photos/seed/health/400/300",
                            Name = "Health Products"
                        },
                        new
                        {
                            CategoryId = 11,
                            ImageUrl = "https://picsum.photos/seed/beauty/400/300",
                            Name = "Beauty Products"
                        },
                        new
                        {
                            CategoryId = 12,
                            ImageUrl = "https://picsum.photos/seed/car/400/300",
                            Name = "Car Accessories"
                        },
                        new
                        {
                            CategoryId = 13,
                            ImageUrl = "https://picsum.photos/seed/books/400/300",
                            Name = "Books"
                        },
                        new
                        {
                            CategoryId = 14,
                            ImageUrl = "https://picsum.photos/seed/music/400/300",
                            Name = "Music Instruments"
                        },
                        new
                        {
                            CategoryId = 15,
                            ImageUrl = "https://picsum.photos/seed/camera/400/300",
                            Name = "Camera Gear"
                        },
                        new
                        {
                            CategoryId = 16,
                            ImageUrl = "https://picsum.photos/seed/toys/400/300",
                            Name = "Kids Toys"
                        },
                        new
                        {
                            CategoryId = 17,
                            ImageUrl = "https://picsum.photos/seed/fashion/400/300",
                            Name = "Fashion"
                        },
                        new
                        {
                            CategoryId = 18,
                            ImageUrl = "https://picsum.photos/seed/outdoor/400/300",
                            Name = "Outdoor"
                        },
                        new
                        {
                            CategoryId = 19,
                            ImageUrl = "https://picsum.photos/seed/pets/400/300",
                            Name = "Pet Supplies"
                        },
                        new
                        {
                            CategoryId = 20,
                            ImageUrl = "https://picsum.photos/seed/cleaning/400/300",
                            Name = "Cleaning Tools"
                        });
                });

            modelBuilder.Entity("MyStore.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Publiser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<DateTime>("Updated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("LastUpdate")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 4,
                            ImageUrl = "https://picsum.photos/seed/mouse/400/300",
                            IsDeleted = false,
                            Name = "Wireless Mouse",
                            Price = 25.5,
                            StockQuantity = 50,
                            Updated = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 4,
                            ImageUrl = "https://picsum.photos/seed/keyboard/400/300",
                            IsDeleted = false,
                            Name = "Mechanical Keyboard",
                            Price = 75.0,
                            StockQuantity = 30,
                            Updated = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 7,
                            ImageUrl = "https://picsum.photos/seed/watch/400/300",
                            IsDeleted = false,
                            Name = "Smart Watch",
                            Price = 120.0,
                            StockQuantity = 20,
                            Updated = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            ImageUrl = "https://picsum.photos/seed/headphones/400/300",
                            IsDeleted = false,
                            Name = "Bluetooth Headphones",
                            Price = 60.0,
                            StockQuantity = 40,
                            Updated = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 4,
                            ImageUrl = "https://picsum.photos/seed/charger/400/300",
                            IsDeleted = false,
                            Name = "USB-C Charger",
                            Price = 18.0,
                            StockQuantity = 100,
                            Updated = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 5,
                            ImageUrl = "https://picsum.photos/seed/controller/400/300",
                            IsDeleted = false,
                            Name = "Gaming Controller",
                            Price = 55.0,
                            StockQuantity = 35,
                            Updated = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 6,
                            ImageUrl = "https://picsum.photos/seed/chair/400/300",
                            IsDeleted = false,
                            Name = "Office Chair",
                            Price = 150.0,
                            StockQuantity = 10,
                            Updated = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 4,
                            ImageUrl = "https://picsum.photos/seed/cooling/400/300",
                            IsDeleted = false,
                            Name = "Laptop Cooling Pad",
                            Price = 30.0,
                            StockQuantity = 45,
                            Updated = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 15,
                            ImageUrl = "https://picsum.photos/seed/lens/400/300",
                            IsDeleted = false,
                            Name = "Camera Lens",
                            Price = 220.0,
                            StockQuantity = 8,
                            Updated = new DateTime(2025, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 1,
                            ImageUrl = "https://picsum.photos/seed/remote/400/300",
                            IsDeleted = false,
                            Name = "TV Remote",
                            Price = 15.0,
                            StockQuantity = 60,
                            Updated = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 8,
                            ImageUrl = "https://picsum.photos/seed/blender/400/300",
                            IsDeleted = false,
                            Name = "Kitchen Blender",
                            Price = 95.0,
                            StockQuantity = 12,
                            Updated = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 9,
                            ImageUrl = "https://picsum.photos/seed/dumbbells/400/300",
                            IsDeleted = false,
                            Name = "Dumbbells Set",
                            Price = 40.0,
                            StockQuantity = 25,
                            Updated = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 12,
                            ImageUrl = "https://picsum.photos/seed/carholder/400/300",
                            IsDeleted = false,
                            Name = "Car Phone Holder",
                            Price = 12.0,
                            StockQuantity = 70,
                            Updated = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 16,
                            ImageUrl = "https://picsum.photos/seed/toycar/400/300",
                            IsDeleted = false,
                            Name = "Toy Car",
                            Price = 20.0,
                            StockQuantity = 80,
                            Updated = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MyStore.Models.ProductImages", b =>
                {
                    b.Property<int>("ProductImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ProductImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MyStore.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MyStore.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyStore.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MyStore.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyStore.Models.Product", b =>
                {
                    b.HasOne("MyStore.Models.Category", "category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("MyStore.Models.ProductImages", b =>
                {
                    b.HasOne("MyStore.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MyStore.Models.Product", b =>
                {
                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
